platform :ios, "8.0"

inhibit_all_warnings!

target :PARTNER, :exclusive => true do

end

# Testing framework for Test target.
target :PARTNERTests, :exclusive => true do
#  pod 'Kiwi/XCTest'
#  pod 'OCMock'
end
