platform :ios, "8.0"

inhibit_all_warnings!

target :PARTNER, :exclusive => true do
	pod "AFNetworking", "~> 2.0"
	pod 'Parse-iOS-SDK'
	pod 'ParseFacebookUtils'
	pod 'MRProgress', '~> 0.7.0'
	pod 'Toast', '~> 2.4’
end

# Testing framework for Test target.
target :PARTNERTests, :exclusive => true do
#  pod 'Kiwi/XCTest'
#  pod 'OCMock'
end
